version: '3.2'

services:
  app:
    build: .
    hostname: app
    restart: unless-stopped
    environment: 
      MONGO_URL: mongodb://root:example@mongodb:27017/
      PORT: 8000
    ports:
      - 8080:8000

  mongodb:
    image: mongo:4.4
    hostname: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
